# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('mainclass', models.CharField(max_length=50)),
                ('subclass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('price', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.Parser'),
        ),
    ]
