# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_auto_20170517_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='website',
        ),
        migrations.AddField(
            model_name='parser',
            name='url',
            field=models.URLField(default='https://shop.usa.canon.com/shop/en/catalog/ef-35mm-f-1-4l-ii-usm-refurbished-l-series-wide-angle-prime-lens'),
            preserve_default=False,
        ),
    ]
