# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_auto_20170523_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='url',
        ),
        migrations.AddField(
            model_name='deal',
            name='website',
            field=models.URLField(default='https://shop.usa.canon.com/shop/en/catalog/ef-35mm-f-1-4l-ii-usm-refurbished-l-series-wide-angle-prime-lens'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
