# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_auto_20170523_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.Deal'),
        ),
    ]
